'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class AspNetUserClaim
        Public Property Id As Integer
        Public Property UserId As Integer
        Public Property ClaimType As String
        Public Property ClaimValue As String
    
        Public Overridable Property AspNetUser As AspNetUser
    
    End Class

End Namespace
