'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class AspNetUser
        Public Property Id As Integer
        Public Property Hometown As String
        Public Property Email As String
        Public Property EmailConfirmed As Nullable(Of Boolean)
        Public Property PasswordHash As String
        Public Property SecurityStamp As String
        Public Property PhoneNumber As String
        Public Property PhoneNumberConfirmed As Nullable(Of Boolean)
        Public Property TwoFactorEnabled As Nullable(Of Boolean)
        Public Property LockoutEndDateUtc As Nullable(Of Date)
        Public Property LockoutEnabled As Nullable(Of Boolean)
        Public Property AccessFailedCount As Nullable(Of Integer)
        Public Property UserName As String
        Public Property LastName As String
        Public Property FirstName As String
        Public Property UserId As String
        Public Property LastLoginDate As Nullable(Of Date)
        Public Property Password2 As String
        Public Property DateofEntry As Nullable(Of Date)
        Public Property IsActive As Nullable(Of Boolean)
    
        Public Overridable Property AspNetUserClaims As ICollection(Of AspNetUserClaim) = New HashSet(Of AspNetUserClaim)
        Public Overridable Property AspNetUserLogins As ICollection(Of AspNetUserLogin) = New HashSet(Of AspNetUserLogin)
        Public Overridable Property AspNetRoles As ICollection(Of AspNetRole) = New HashSet(Of AspNetRole)
        Public Overridable Property UserHistories As ICollection(Of UserHistory) = New HashSet(Of UserHistory)
    
    End Class

End Namespace
