'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class ChangeLog
        Public Property ChangeLogID As Integer
        Public Property EntityName As String
        Public Property PropertyName As String
        Public Property PrimaryKeyValue As String
        Public Property OldValue As String
        Public Property NewValue As String
        Public Property DateChanged As Nullable(Of Date)
    
    End Class

End Namespace
