'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class ClientContact
        Public Property Account__ As String
        Public Property Name_of_Facility As String
        Public Property Group_Name As String
        Public Property First_Name As String
        Public Property Last_Name As String
        Public Property Column_5 As String
        Public Property Job_Title As String
        Public Property Email As String
        Public Property Facility__ As String
        Public Property Admin_Cell__ As String
        Public Property Full_Address As String
        Public Property Street_Address As String
        Public Property City As String
        Public Property State As String
        Public Property Zip As String
        Public Property C__of_beds As String
        Public Property Shift_Change As String
        Public Property ID As Integer
        Public Property DateofEntry As Nullable(Of Date)
        Public Property ValidEmail As Nullable(Of Boolean)
        Public Property Email2 As String
    
    End Class

End Namespace
