'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class CovidMemo
        Public Property MemoID As Integer
        Public Property MemoName As String
        Public Property MemoPath As String
        Public Property DateSent As Nullable(Of Date)
    
    End Class

End Namespace
