'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class CovidTool
        Public Property ToolID As Integer
        Public Property ToolName As String
        Public Property MemoID As Nullable(Of Integer)
        Public Property ToolPath As String
    
    End Class

End Namespace
