'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class FacilityOwner
        Public Property FacilityOwnerID As Integer
        Public Property FacilityGroupID As Integer
        Public Property UserID As Integer
        Public Property UserEditor As String
        Public Property DateCreated As Nullable(Of Date)
        Public Property DateModified As Nullable(Of Date)
    
        Public Overridable Property User As User
    
    End Class

End Namespace
