'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class FacilityUserRole
        Public Property FacilityGroupID As Integer
        Public Property FacilityID As Integer
        Public Property Title As String
        Public Property EmailAddress As String
        Public Property TitleOrder As Nullable(Of Integer)
        Public Property Description As String
        Public Property JobTitleID As Integer
    
    End Class

End Namespace
