'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class FacilityUser
        Public Property FacilityUserID As Integer
        Public Property FacilityID As Integer
        Public Property UserID As Integer
        Public Property InActive As Nullable(Of Boolean)
        Public Property Roles As String
        Public Property UserEditor As String
        Public Property DateCreated As Nullable(Of Date)
        Public Property DateModified As Nullable(Of Date)
        Public Property del As Nullable(Of Boolean)
        Public Property RolesID As String
    
        Public Overridable Property Facility As Facility
        Public Overridable Property User As User
        Public Overridable Property FacilityUsersJobs As ICollection(Of FacilityUsersJob) = New HashSet(Of FacilityUsersJob)
    
    End Class

End Namespace
