'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class FacilityGroup
        Public Property FacilityGroupID As Integer
        Public Property GroupName As String
        Public Property InActive As Nullable(Of Boolean)
        Public Property UserEditor As String
        Public Property DateCreated As Nullable(Of Date)
        Public Property DateModified As Nullable(Of Date)
        Public Property AllowPolicyPrint As Nullable(Of Boolean)
    
        Public Overridable Property Facilities As ICollection(Of Facility) = New HashSet(Of Facility)
    
    End Class

End Namespace
