'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class GetFacility
        Public Property FacilityGroupID As Integer
        Public Property FacilityID As Integer
        Public Property GroupName As String
        Public Property FacilityName As String
        Public Property State As String
        Public Property InActive As Nullable(Of Boolean)
        Public Property Address As String
        Public Property City As String
        Public Property Zip As String
        Public Property Beds As String
        Public Property ShiftChange As String
        Public Property Phone1 As String
        Public Property Fax As String
        Public Property FacilityGroupName As String
    
    End Class

End Namespace
