'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class GetUser
        Public Property FacilityGroupID As Integer
        Public Property FacilityID As Integer
        Public Property FacilityUserID As Integer
        Public Property UserID As Integer
        Public Property GroupName As String
        Public Property FacilityName As String
        Public Property LastName As String
        Public Property FirstName As String
        Public Property InActive As Nullable(Of Boolean)
        Public Property EmailAddress As String
        Public Property Phone1 As String
        Public Property Phone2 As String
        Public Property State As String
        Public Property Roles As String
        Public Property RolesID As String
    
    End Class

End Namespace
