'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class JobTitle
        Public Property JobTitleID As Integer
        Public Property RoleID As Nullable(Of Integer)
        Public Property Title As String
        Public Property TitleOrder As Nullable(Of Integer)
        Public Property Description As String
        Public Property DateofEntry As Nullable(Of Date)
    
        Public Overridable Property FacilityUsersJobs As ICollection(Of FacilityUsersJob) = New HashSet(Of FacilityUsersJob)
    
    End Class

End Namespace
