'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class SectionIndex
        Public Property SectionIndexID As Integer
        Public Property State As String
        Public Property PolicyNo As String
        Public Property SectionFrom As Nullable(Of Integer)
        Public Property SectionTo As Nullable(Of Integer)
    
    End Class

End Namespace
