'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class StaffMember
        Public Property StaffMembersID As Integer
        Public Property FacilityGroupID As Nullable(Of Integer)
        Public Property FacilityID As Nullable(Of Integer)
        Public Property GroupName As String
        Public Property FacilityName As String
        Public Property EmailAddress As String
        Public Property DateAdded As Nullable(Of Date)
    
    End Class

End Namespace
