'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class User
        Public Property UserID As Integer
        Public Property AspNetUserID As Nullable(Of Integer)
        Public Property InActive As Nullable(Of Boolean)
        Public Property UserName As String
        Public Property LastName As String
        Public Property FirstName As String
        Public Property EmailAddress As String
        Public Property Phone1 As String
        Public Property Phone2 As String
        Public Property ProfileImage As Byte()
        Public Property ProfileImagePath As String
        Public Property JobTitle As String
        Public Property JobTitle2 As String
        Public Property UserEditor As String
        Public Property DateCreated As Nullable(Of Date)
        Public Property DateModified As Nullable(Of Date)
        Public Property Password As String
        Public Property Del As Nullable(Of Boolean)
        Public Property ValidEmail As Nullable(Of Boolean)
    
        Public Overridable Property FacilityOwners As ICollection(Of FacilityOwner) = New HashSet(Of FacilityOwner)
        Public Overridable Property FacilityUsers As ICollection(Of FacilityUser) = New HashSet(Of FacilityUser)
    
    End Class

End Namespace
