'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class UserHistory
        Public Property UserHistoryID As Integer
        Public Property UserID As Nullable(Of Integer)
        Public Property UserName As String
        Public Property Login As Nullable(Of Date)
        Public Property Logoff As Nullable(Of Date)
        Public Property Success As Nullable(Of Boolean)
        Public Property SignInStatus As Nullable(Of Integer)
        Public Property URL As String
        Public Property Activity As String
        Public Property UserAgent As String
        Public Property IPAddress As String
        Public Property DateofEntry As Nullable(Of Date)
    
        Public Overridable Property AspNetUser As AspNetUser
    
    End Class

End Namespace
