'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CCGData

    Partial Public Class UsersByTitle
        Public Property UserID As Integer
        Public Property LastName As String
        Public Property FirstName As String
        Public Property JobTitleID As Integer
        Public Property Title As String
        Public Property InActive As Nullable(Of Boolean)
        Public Property EmailAddress As String
        Public Property Phone1 As String
        Public Property Phone2 As String
        Public Property FacilityName As String
    
    End Class

End Namespace
