'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("compliancecg.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unknown failure has occured..
        '''</summary>
        Friend Shared ReadOnly Property DefaultError() As String
            Get
                Return ResourceManager.GetString("DefaultError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email &apos;{0}&apos; is already taken..
        '''</summary>
        Friend Shared ReadOnly Property DuplicateEmail() As String
            Get
                Return ResourceManager.GetString("DuplicateEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name {0} is already taken..
        '''</summary>
        Friend Shared ReadOnly Property DuplicateName() As String
            Get
                Return ResourceManager.GetString("DuplicateName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A user with that external login already exists..
        '''</summary>
        Friend Shared ReadOnly Property ExternalLoginExists() As String
            Get
                Return ResourceManager.GetString("ExternalLoginExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email &apos;{0}&apos; is invalid..
        '''</summary>
        Friend Shared ReadOnly Property InvalidEmail() As String
            Get
                Return ResourceManager.GetString("InvalidEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid token..
        '''</summary>
        Friend Shared ReadOnly Property InvalidToken() As String
            Get
                Return ResourceManager.GetString("InvalidToken", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User name {0} is invalid, can only contain letters or digits..
        '''</summary>
        Friend Shared ReadOnly Property InvalidUserName() As String
            Get
                Return ResourceManager.GetString("InvalidUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lockout is not enabled for this user..
        '''</summary>
        Friend Shared ReadOnly Property LockoutNotEnabled() As String
            Get
                Return ResourceManager.GetString("LockoutNotEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No IUserTokenProvider is registered..
        '''</summary>
        Friend Shared ReadOnly Property NoTokenProvider() As String
            Get
                Return ResourceManager.GetString("NoTokenProvider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No IUserTwoFactorProvider for &apos;{0}&apos; is registered..
        '''</summary>
        Friend Shared ReadOnly Property NoTwoFactorProvider() As String
            Get
                Return ResourceManager.GetString("NoTwoFactorProvider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incorrect password..
        '''</summary>
        Friend Shared ReadOnly Property PasswordMismatch() As String
            Get
                Return ResourceManager.GetString("PasswordMismatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        '''</summary>
        Friend Shared ReadOnly Property PasswordRequireDigit() As String
            Get
                Return ResourceManager.GetString("PasswordRequireDigit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)..
        '''</summary>
        Friend Shared ReadOnly Property PasswordRequireLower() As String
            Get
                Return ResourceManager.GetString("PasswordRequireLower", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passwords must have at least one non letter or digit character..
        '''</summary>
        Friend Shared ReadOnly Property PasswordRequireNonLetterOrDigit() As String
            Get
                Return ResourceManager.GetString("PasswordRequireNonLetterOrDigit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        '''</summary>
        Friend Shared ReadOnly Property PasswordRequireUpper() As String
            Get
                Return ResourceManager.GetString("PasswordRequireUpper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passwords must be at least {0} characters..
        '''</summary>
        Friend Shared ReadOnly Property PasswordTooShort() As String
            Get
                Return ResourceManager.GetString("PasswordTooShort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} cannot be null or empty..
        '''</summary>
        Friend Shared ReadOnly Property PropertyTooShort() As String
            Get
                Return ResourceManager.GetString("PropertyTooShort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Role {0} does not exist..
        '''</summary>
        Friend Shared ReadOnly Property RoleNotFound() As String
            Get
                Return ResourceManager.GetString("RoleNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IQueryableRoleStore&lt;TRole&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIQueryableRoleStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIQueryableRoleStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IQueryableUserStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIQueryableUserStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIQueryableUserStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IUserClaimStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIUserClaimStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIUserClaimStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IUserConfirmationStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIUserConfirmationStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIUserConfirmationStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IUserEmailStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIUserEmailStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIUserEmailStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IUserLockoutStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIUserLockoutStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIUserLockoutStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IUserLoginStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIUserLoginStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIUserLoginStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IUserPasswordStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIUserPasswordStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIUserPasswordStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IUserPhoneNumberStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIUserPhoneNumberStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIUserPhoneNumberStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IUserRoleStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIUserRoleStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIUserRoleStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IUserSecurityStampStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIUserSecurityStampStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIUserSecurityStampStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Store does not implement IUserTwoFactorStore&lt;TUser&gt;..
        '''</summary>
        Friend Shared ReadOnly Property StoreNotIUserTwoFactorStore() As String
            Get
                Return ResourceManager.GetString("StoreNotIUserTwoFactorStore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User already has a password set..
        '''</summary>
        Friend Shared ReadOnly Property UserAlreadyHasPassword() As String
            Get
                Return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User already in role..
        '''</summary>
        Friend Shared ReadOnly Property UserAlreadyInRole() As String
            Get
                Return ResourceManager.GetString("UserAlreadyInRole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserId not found..
        '''</summary>
        Friend Shared ReadOnly Property UserIdNotFound() As String
            Get
                Return ResourceManager.GetString("UserIdNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User {0} does not exist..
        '''</summary>
        Friend Shared ReadOnly Property UserNameNotFound() As String
            Get
                Return ResourceManager.GetString("UserNameNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User is not in role..
        '''</summary>
        Friend Shared ReadOnly Property UserNotInRole() As String
            Get
                Return ResourceManager.GetString("UserNotInRole", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
